-- Bootst de tabelstructuur na zoals die in productie bleek te staan: een
-- overblijfsel van een eerdere versie van het schema, waarin member_id in
-- een samengestelde primaire sleutel (pool_id, member_id) zit.
--
-- member_id is dan op zichzelf niet uniek, en Postgres weigert de foreign
-- key van predictions ernaartoe met:
--   42830: there is no unique constraint matching given keys for
--          referenced table "pool_members"
--
-- schema.sql hoort dit recht te zetten zonder de bestaande gegevens te
-- raken. oude-structuur-controle.sql controleert dat daarna.

\set ON_ERROR_STOP on

create extension if not exists pgcrypto;

create table pools (
  id        uuid primary key default gen_random_uuid(),
  name      text,
  join_code text unique
);

create table pool_members (
  pool_id      uuid not null,
  member_id    uuid not null default gen_random_uuid(),
  display_name text,
  primary key (pool_id, member_id)
);

create table races (
  id     bigint generated by default as identity primary key,
  season int,
  round  int,
  name   text
);

create table predictions (
  pool_id     uuid,
  race_id     bigint,
  member_id   uuid,
  quali_top10 text[],
  race_top10  text[]
);

insert into pools (name, join_code) values ('Vrijdagmiddagpoule', 'RTM026');
insert into pool_members (pool_id, display_name) select id, 'Danny' from pools;
insert into races (season, round, name) values (2026, 1, 'Melbourne');
