-- ============================================================
--  F1 Poule — databaseschema
--  Plak dit in de Supabase SQL editor en draai het.
--
--  Het script is opnieuw te draaien op een bestaande database. Het maakt
--  ontbrekende tabellen en kolommen aan, herstelt de sleutels en policies,
--  en laat onderaan zien of alles klopt. Bestaande voorspellingen blijven
--  staan; alleen rijen die de app toch niet kan tonen (exacte dubbelen en
--  rijen zonder speler of race) worden opgeruimd, met een melding erbij.
--
--  Werkt het daarna nog niet, dan wijkt de oude tabelstructuur te ver af.
--  Draai in dat geval eerst reset.sql en daarna dit bestand opnieuw.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
--  Tabellen
-- ------------------------------------------------------------

create table if not exists public.pools (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  season     int  not null default 2026,
  join_code  text not null unique default upper(substr(md5(random()::text), 1, 6)),
  created_at timestamptz not null default now()
);

create table if not exists public.pool_members (
  member_id    uuid primary key default gen_random_uuid(),
  pool_id      uuid not null,
  display_name text not null,
  created_at   timestamptz not null default now()
);

create table if not exists public.races (
  id             bigint generated by default as identity primary key,
  season         int  not null,
  round          int  not null,
  name           text not null,
  country        text,
  race_key       bigint,
  quali_key      bigint,
  deadline_quali timestamptz,
  deadline_race  timestamptz,
  drivers        jsonb,
  quali_result   text[],
  race_result    text[],
  -- Met de hand ingevoerd in plaats van opgehaald bij OpenF1. De sync vult
  -- alleen lege uitslagen, dus zo'n uitslag wordt nooit meer automatisch
  -- gecorrigeerd; daarom moet zichtbaar zijn welke het zijn.
  quali_handmatig boolean not null default false,
  race_handmatig  boolean not null default false,
  -- Losse uitslagen: één coureurnummer per stuk.
  fastest_lap               text,
  fastest_pitstop           text,
  fastest_lap_handmatig     boolean not null default false,
  fastest_pitstop_handmatig boolean not null default false,
  -- Twee uitslagen die niets met een coureur te maken hebben.
  safety_cars               int,
  rode_vlag                 boolean,
  safety_cars_handmatig     boolean not null default false,
  rode_vlag_handmatig       boolean not null default false
);

create table if not exists public.predictions (
  pool_id     uuid   not null,
  race_id     bigint not null,
  member_id   uuid   not null,
  quali_top10 text[],
  race_top10  text[],
  -- De winnaar apart, 25 punten. Hangt aan de race-deadline, net als
  -- race_top10, en wordt door dezelfde trigger bewaakt.
  race_winnaar text,
  updated_at  timestamptz not null default now()
);

-- ------------------------------------------------------------
--  Vragen
--  Zie BEDIENING.md. Vaste kolommen werken tot een stuk of drie vragen;
--  daarboven is een rij per vraag eenvoudiger, en pas dan kan een poule
--  zelf kiezen wat er meedoet.
--
--  De app leest en schrijft deze tabellen sinds de migratie; de kolommen
--  op predictions hierboven staan er alleen nog voor de oude gegevens.
-- ------------------------------------------------------------

create table if not exists public.questions (
  id       text primary key,   -- 'quali_top10', 'winnaar', ...
  naam     text not null,
  punten   int  not null,      -- maximaal haalbaar per weekend
  sessie   text not null,      -- 'quali' of 'race': aan welke deadline hij hangt
  soort    text not null,      -- 'top10' | 'coureur' | 'getal' | 'janee' | 'duels'
  -- Gokvragen scoren hoog per stuk maar hangen van geluk af. BEDIENING.md §8
  -- wil waarschuwen zodra ze samen boven 30% van het maximum uitkomen, en
  -- daarvoor moet ergens vastliggen wélke dat zijn.
  gok      boolean not null default false,
  volgorde int  not null default 0
);

-- Welke vragen doen mee in een poule. Aanwezig = aan; dat scheelt een
-- boolean die altijd op true zou staan.
create table if not exists public.pool_questions (
  pool_id     uuid not null,
  question_id text not null,
  primary key (pool_id, question_id)
);

-- Eén rij per ingevulde vraag, in plaats van een kolom per vraagsoort.
-- waarde is jsonb omdat een top 10 een lijst is, een winnaar een tekst,
-- het aantal safety cars een getal en de rode vlag een ja of nee.
create table if not exists public.answers (
  pool_id     uuid   not null,
  race_id     bigint not null,
  member_id   uuid   not null,
  question_id text   not null,
  waarde      jsonb  not null,
  updated_at  timestamptz not null default now(),
  primary key (pool_id, race_id, member_id, question_id)
);

-- ------------------------------------------------------------
--  Kolommen bijwerken
--  Het schema is tijdens de bouw meerdere keren veranderd en
--  "create table if not exists" past een bestaande tabel niet aan.
-- ------------------------------------------------------------

alter table public.pools        add column if not exists season     int not null default 2026;
alter table public.pools        add column if not exists join_code  text;
alter table public.pools        add column if not exists created_at timestamptz not null default now();
-- Wie de poule heeft aangemaakt. Zonder login kan de database dit niet
-- afdwingen; het is er om ongelukken te voorkomen, niet kwaadwilligheid.
-- Wie de anon key uit de broncode plukt komt er alsnog omheen. Zie
-- BEDIENING.md §7.
alter table public.pools        add column if not exists owner_member_id uuid;
-- Zodra de eerste race gescoord is ligt de vragenset vast, anders zijn de
-- races onderling niet meer vergelijkbaar.
alter table public.pools        add column if not exists questions_locked boolean not null default false;

alter table public.pool_members add column if not exists pool_id      uuid;
alter table public.pool_members add column if not exists display_name text;
alter table public.pool_members add column if not exists created_at   timestamptz not null default now();

alter table public.races        add column if not exists country        text;
alter table public.races        add column if not exists race_key       bigint;
alter table public.races        add column if not exists quali_key      bigint;
alter table public.races        add column if not exists deadline_quali timestamptz;
alter table public.races        add column if not exists deadline_race  timestamptz;
alter table public.races        add column if not exists drivers        jsonb;
alter table public.races        add column if not exists quali_result   text[];
alter table public.races        add column if not exists race_result    text[];
alter table public.races        add column if not exists quali_handmatig boolean not null default false;
alter table public.races        add column if not exists race_handmatig  boolean not null default false;
-- Losse uitslagen die niet uit een volgorde te halen zijn: één coureurnummer.
-- De sync vult alleen wat leeg is, dus wat hier met de hand in gaat blijft
-- staan; de vlag is er om dat op het scherm te kunnen zeggen.
alter table public.races        add column if not exists fastest_lap               text;
alter table public.races        add column if not exists fastest_pitstop           text;
alter table public.races        add column if not exists fastest_lap_handmatig     boolean not null default false;
alter table public.races        add column if not exists fastest_pitstop_handmatig boolean not null default false;
-- En twee die niets met een coureur te maken hebben. Allebei mogen ze null
-- zijn: dat betekent "nog niet bekend", en 0 safety cars is iets anders.
alter table public.races        add column if not exists safety_cars               int;
alter table public.races        add column if not exists rode_vlag                 boolean;
alter table public.races        add column if not exists safety_cars_handmatig     boolean not null default false;
alter table public.races        add column if not exists rode_vlag_handmatig       boolean not null default false;

alter table public.predictions  add column if not exists quali_top10 text[];
alter table public.predictions  add column if not exists race_top10  text[];
alter table public.predictions  add column if not exists race_winnaar text;
alter table public.predictions  add column if not exists updated_at  timestamptz not null default now();

-- ------------------------------------------------------------
--  De vragenlijst
--  Punten per weekend. De presets uit BEDIENING.md §3 tellen hiermee op
--  tot 100 (Simpel), 145 (Klassiek) en 202 (Gevorderd).
--  Opnieuw uit te voeren: bestaande rijen worden bijgewerkt, niet gedupliceerd.
-- ------------------------------------------------------------

insert into public.questions (id, naam, punten, sessie, soort, gok, volgorde) values
  ('quali_top10',      'Top 10 kwalificatie', 50, 'quali', 'top10',   false, 10),
  ('race_top10',       'Top 10 race',         50, 'race',  'top10',   false, 20),
  ('winnaar',          'Winnaar',             25, 'race',  'coureur', false, 30),
  ('pole',             'Pole position',       10, 'quali', 'coureur', false, 40),
  ('snelste_ronde',    'Snelste ronde',       10, 'race',  'coureur', false, 50),
  ('snelste_pitstop',  'Snelste pitstop',     10, 'race',  'coureur', false, 60),
  ('teamgenoot_duels', 'Teamgenoot-duels',    15, 'race',  'duels',   false, 70),
  ('safety_cars',      'Aantal safety cars',  12, 'race',  'getal',   true,  80),
  ('rode_vlag',        'Rode vlag',           20, 'race',  'janee',   true,  90)
on conflict (id) do update set
  naam = excluded.naam, punten = excluded.punten, sessie = excluded.sessie,
  soort = excluded.soort, gok = excluded.gok, volgorde = excluded.volgorde;

-- poules zonder code kunnen niet gevonden worden
update public.pools set join_code = upper(substr(md5(random()::text), 1, 6))
where join_code is null;

alter table public.pools alter column join_code set not null;
alter table public.pools alter column join_code set default upper(substr(md5(random()::text), 1, 6));

-- ------------------------------------------------------------
--  Opruimen voor de sleutels erop kunnen
--  Alleen rijen die index.html sowieso niet kan tonen of scoren.
-- ------------------------------------------------------------

do $$
declare weg int;
begin
  -- Voorspellingen zonder poule, race of speler zijn niet te koppelen.
  delete from public.predictions
  where pool_id is null or race_id is null or member_id is null;
  get diagnostics weg = row_count;
  if weg > 0 then raise notice 'onbruikbare voorspellingen verwijderd: %', weg; end if;

  -- Wijzen naar een race, poule of speler die niet meer bestaat.
  delete from public.predictions p
  where not exists (select 1 from public.races        r where r.id = p.race_id)
     or not exists (select 1 from public.pools        o where o.id = p.pool_id)
     or not exists (select 1 from public.pool_members m where m.member_id = p.member_id);
  get diagnostics weg = row_count;
  if weg > 0 then raise notice 'verweesde voorspellingen verwijderd: %', weg; end if;

  -- Dubbelen ontstaan doordat een upsert zonder unieke sleutel elke keer
  -- een nieuwe rij aanmaakte. De laatst bijgewerkte rij is de goede.
  delete from public.predictions p
  using public.predictions q
  where p.pool_id = q.pool_id and p.race_id = q.race_id and p.member_id = q.member_id
    and (p.updated_at, p.ctid) < (q.updated_at, q.ctid);
  get diagnostics weg = row_count;
  if weg > 0 then raise notice 'dubbele voorspellingen opgeruimd: %', weg; end if;
end $$;

-- ------------------------------------------------------------
--  Van predictions naar answers
--  De app schrijft voorspellingen nu weg als één rij per vraag. Bestaande
--  voorspellingen verhuizen hier mee, zodat niemand zijn ingevulde races
--  kwijtraakt. Opnieuw uit te voeren: al verhuisde rijen blijven staan en
--  worden niet overschreven, want daar staat inmiddels de nieuwste versie.
--  De deadline-trigger gaat er even uit: deze voorspellingen zijn destijds
--  op tijd ingevuld, en een race van vorig jaar zou nu geweigerd worden.
--  Bij de allereerste run bestaat die trigger nog niet.
-- ------------------------------------------------------------

do $$
declare over int; met_trigger boolean;
begin
  select exists (
    select 1 from pg_trigger
    where tgrelid = 'public.answers'::regclass and tgname = 'answers_deadline'
  ) into met_trigger;
  if met_trigger then alter table public.answers disable trigger answers_deadline; end if;

  insert into public.answers (pool_id, race_id, member_id, question_id, waarde, updated_at)
  select p.pool_id, p.race_id, p.member_id, v.question_id, v.waarde, p.updated_at
  from public.predictions p
  cross join lateral (values
      ('quali_top10'::text, to_jsonb(p.quali_top10)),
      ('race_top10',  to_jsonb(p.race_top10)),
      ('winnaar',     to_jsonb(p.race_winnaar))
    ) as v(question_id, waarde)
  -- Een lege lijst is "niet ingevuld", geen antwoord van nul coureurs.
  where v.waarde is not null and v.waarde <> 'null'::jsonb and v.waarde <> '[]'::jsonb
  on conflict (pool_id, race_id, member_id, question_id) do nothing;
  get diagnostics over = row_count;
  if over > 0 then raise notice 'voorspellingen overgezet naar answers: %', over; end if;

  if met_trigger then alter table public.answers enable trigger answers_deadline; end if;
end $$;

-- ------------------------------------------------------------
--  Sleutels
--  Zonder de unieke sleutel op predictions wordt elke "wijziging" een
--  nieuwe rij en lijkt bewaren willekeurig wel en niet te werken.
-- ------------------------------------------------------------

alter table public.races       drop constraint if exists races_seizoen_ronde;
alter table public.races        add constraint races_seizoen_ronde unique (season, round);

alter table public.predictions drop constraint if exists predictions_uniek;
alter table public.predictions  add constraint predictions_uniek
  unique (pool_id, race_id, member_id);

-- Een foreign key eist een unieke sleutel op precies de kolom waarnaar hij
-- wijst. In een oudere tabelstructuur zit member_id soms in een samengestelde
-- primaire sleutel (pool_id, member_id); dan is member_id op zichzelf niet
-- uniek en weigert Postgres de foreign key met 42830. Hieronder wordt dat
-- rechtgezet zonder de bestaande sleutel aan te tasten.
do $$
declare
  doel   record;
  leeg   bigint;
  dubbel bigint;
begin
  for doel in
    select * from (values
      ('pool_members', 'member_id'),
      ('pools',        'id'),
      ('races',        'id')
    ) as v(tabel, kolom)
  loop
    -- Al een sleutel op precies deze ene kolom? Dan is er niets te doen.
    if exists (
      select 1 from (
        select tc.constraint_name,
               count(*)                as aantal,
               min(kcu.column_name)    as kolom
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on  kcu.constraint_name   = tc.constraint_name
          and kcu.constraint_schema = tc.constraint_schema
        where tc.table_schema = 'public'
          and tc.table_name   = doel.tabel
          and tc.constraint_type in ('PRIMARY KEY', 'UNIQUE')
        group by tc.constraint_name
      ) s
      where s.aantal = 1 and s.kolom = doel.kolom
    ) then
      continue;
    end if;

    execute format('select count(*) from public.%I where %I is null', doel.tabel, doel.kolom)
      into leeg;
    execute format(
      'select count(*) from (select 1 from public.%I group by %I having count(*) > 1) d',
      doel.tabel, doel.kolom) into dubbel;

    if leeg > 0 or dubbel > 0 then
      raise exception
        'De kolom %.% kan geen sleutel worden: % lege en % dubbele waarden. '
        'De tabel komt uit een oudere opzet die te ver afwijkt. '
        'Draai reset.sql en daarna schema.sql opnieuw.',
        doel.tabel, doel.kolom, leeg, dubbel;
    end if;

    execute format('alter table public.%I add constraint %I unique (%I)',
                   doel.tabel, doel.tabel || '_' || doel.kolom || '_uniek', doel.kolom);
    raise notice 'oudere structuur bijgewerkt: unieke sleutel toegevoegd op %.%',
      doel.tabel, doel.kolom;
  end loop;
end $$;

alter table public.pool_members drop constraint if exists pool_members_pool_fk;
alter table public.pool_members  add constraint pool_members_pool_fk
  foreign key (pool_id) references public.pools(id) on delete cascade;

alter table public.predictions drop constraint if exists predictions_pool_fk;
alter table public.predictions  add constraint predictions_pool_fk
  foreign key (pool_id) references public.pools(id) on delete cascade;

alter table public.predictions drop constraint if exists predictions_race_fk;
alter table public.predictions  add constraint predictions_race_fk
  foreign key (race_id) references public.races(id) on delete cascade;

alter table public.predictions drop constraint if exists predictions_member_fk;
alter table public.predictions  add constraint predictions_member_fk
  foreign key (member_id) references public.pool_members(member_id) on delete cascade;

-- Alles wat aan een poule hangt gaat mee als die poule weggaat, net als
-- pool_members en predictions hierboven.
alter table public.pool_questions drop constraint if exists pool_questions_pool_fk;
alter table public.pool_questions  add constraint pool_questions_pool_fk
  foreign key (pool_id) references public.pools(id) on delete cascade;
alter table public.pool_questions drop constraint if exists pool_questions_vraag_fk;
alter table public.pool_questions  add constraint pool_questions_vraag_fk
  foreign key (question_id) references public.questions(id) on delete cascade;

alter table public.answers drop constraint if exists answers_pool_fk;
alter table public.answers  add constraint answers_pool_fk
  foreign key (pool_id) references public.pools(id) on delete cascade;
alter table public.answers drop constraint if exists answers_race_fk;
alter table public.answers  add constraint answers_race_fk
  foreign key (race_id) references public.races(id) on delete cascade;
alter table public.answers drop constraint if exists answers_member_fk;
alter table public.answers  add constraint answers_member_fk
  foreign key (member_id) references public.pool_members(member_id) on delete cascade;
alter table public.answers drop constraint if exists answers_vraag_fk;
alter table public.answers  add constraint answers_vraag_fk
  foreign key (question_id) references public.questions(id) on delete cascade;

create index if not exists answers_pool_race_idx on public.answers (pool_id, race_id);
create index if not exists predictions_pool_idx on public.predictions (pool_id);
create index if not exists pool_members_pool_idx on public.pool_members (pool_id);
create index if not exists races_seizoen_idx on public.races (season, round);

-- ------------------------------------------------------------
--  Deadline
--  Dit is de enige regel die echt in de database wordt afgedwongen.
--
--  Belangrijk: er wordt op een *wijziging* getest, niet op de aanwezigheid
--  van de kolom. Anders kun je je race-top-10 niet meer opslaan zodra de
--  kwalificatie is begonnen, omdat het opslaan de ongewijzigde
--  kwalificatiekolom meestuurt.
-- ------------------------------------------------------------

create or replace function public.poule_deadline_bewaken()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  d_quali timestamptz;
  d_race  timestamptz;
begin
  select deadline_quali, deadline_race into d_quali, d_race
  from public.races where id = new.race_id;

  if not found then
    raise exception 'Race % bestaat niet', new.race_id;
  end if;

  if tg_op = 'INSERT' then
    if new.quali_top10 is not null and d_quali is not null and now() > d_quali then
      raise exception 'De kwalificatie van deze race is gesloten';
    end if;
    if (new.race_top10 is not null or new.race_winnaar is not null)
       and d_race is not null and now() > d_race then
      raise exception 'De race is gesloten';
    end if;
  else
    if new.quali_top10 is distinct from old.quali_top10
       and d_quali is not null and now() > d_quali then
      raise exception 'De kwalificatie van deze race is gesloten';
    end if;
    if (new.race_top10   is distinct from old.race_top10
        or new.race_winnaar is distinct from old.race_winnaar)
       and d_race is not null and now() > d_race then
      raise exception 'De race is gesloten';
    end if;
  end if;

  new.updated_at = now();
  return new;
end $$;

drop trigger if exists predictions_deadline on public.predictions;
create trigger predictions_deadline
  before insert or update on public.predictions
  for each row execute function public.poule_deadline_bewaken();

-- Dezelfde bewaking voor answers. De deadline is het enige wat hier hard in
-- de database is afgedwongen, dus die mag niet wegvallen doordat de app naar
-- een andere tabel schrijft. Welke deadline geldt hangt af van de vraag:
-- questions.sessie zegt of hij aan de kwalificatie of aan de race hangt.
create or replace function public.poule_antwoord_deadline()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  sessie_van text;
  deadline   timestamptz;
begin
  -- Een ongewijzigd antwoord opnieuw wegschrijven mag altijd; anders
  -- blokkeert een verstreken deadline het opslaan van een ándere vraag.
  if tg_op = 'UPDATE' and new.waarde is not distinct from old.waarde then
    new.updated_at = now();
    return new;
  end if;

  -- Kent de database deze vraag of race niet, dan weigeren de foreign keys
  -- de rij zo meteen zelf met een nette 23503, waar index.html een leesbare
  -- melding van maakt. Hier al een eigen fout gooien zou die overschaduwen.
  select q.sessie into sessie_van from public.questions q where q.id = new.question_id;
  if not found then return new; end if;

  select case when sessie_van = 'quali' then r.deadline_quali else r.deadline_race end
    into deadline
  from public.races r where r.id = new.race_id;
  if not found then return new; end if;

  if deadline is not null and now() > deadline then
    if sessie_van = 'quali' then
      raise exception 'De kwalificatie van deze race is gesloten';
    else
      raise exception 'De race is gesloten';
    end if;
  end if;

  new.updated_at = now();
  return new;
end $$;

drop trigger if exists answers_deadline on public.answers;
create trigger answers_deadline
  before insert or update on public.answers
  for each row execute function public.poule_antwoord_deadline();

-- ------------------------------------------------------------
--  Toegang
--  Er is geen login: de poulecode is de enige drempel. Alles staat dus
--  open voor de anon-sleutel. Dat is een bewuste keuze, zie OVERDRACHT.md.
--  De deadline hierboven is wel hard afgedwongen.
-- ------------------------------------------------------------

alter table public.pools        enable row level security;
alter table public.pool_members enable row level security;
alter table public.races        enable row level security;
alter table public.predictions  enable row level security;
alter table public.questions      enable row level security;
alter table public.pool_questions enable row level security;
alter table public.answers        enable row level security;

drop policy if exists pools_open        on public.pools;
drop policy if exists pool_members_open on public.pool_members;
drop policy if exists races_open        on public.races;
drop policy if exists races_all         on public.races;
drop policy if exists predictions_open  on public.predictions;
drop policy if exists questions_lezen   on public.questions;
drop policy if exists pool_questions_open on public.pool_questions;
drop policy if exists answers_open      on public.answers;

create policy pools_open        on public.pools
  for all to anon, authenticated using (true) with check (true);
create policy pool_members_open on public.pool_members
  for all to anon, authenticated using (true) with check (true);
-- races staat ook open voor schrijven omdat sync.html in de browser draait
-- en dus alleen de anon-sleutel heeft.
create policy races_open        on public.races
  for all to anon, authenticated using (true) with check (true);
create policy predictions_open  on public.predictions
  for all to anon, authenticated using (true) with check (true);
-- De vragenlijst zelf is de enige tabel die niet openstaat voor schrijven:
-- die hoort uit schema.sql te komen, niet uit de app. Lezen mag wel, want
-- de app moet de namen en punten kunnen tonen.
create policy questions_lezen   on public.questions
  for select to anon, authenticated using (true);
create policy pool_questions_open on public.pool_questions
  for all to anon, authenticated using (true) with check (true);
create policy answers_open      on public.answers
  for all to anon, authenticated using (true) with check (true);

-- ------------------------------------------------------------
--  Controle
--  Hieronder moet overal 'ok' staan.
-- ------------------------------------------------------------

select 'unieke sleutel op predictions' as controle,
       case when exists (
         select 1 from pg_constraint
         where conrelid = 'public.predictions'::regclass
           and conname = 'predictions_uniek'
       ) then 'ok' else 'ONTBREEKT' end as uitkomst
union all
select 'deadline-trigger',
       case when exists (
         select 1 from pg_trigger
         where tgrelid = 'public.predictions'::regclass
           and tgname = 'predictions_deadline'
       ) then 'ok' else 'ONTBREEKT' end
union all
select 'deadline-trigger op answers',
       case when exists (
         select 1 from pg_trigger
         where tgrelid = 'public.answers'::regclass
           and tgname = 'answers_deadline'
       ) then 'ok' else 'ONTBREEKT' end
union all
select 'dubbele voorspellingen',
       case when (select count(*) from (
         select 1 from public.predictions
         group by pool_id, race_id, member_id having count(*) > 1) d) = 0
       then 'ok' else 'NOG AANWEZIG' end
union all
select 'aantal poules',        (select count(*)::text from public.pools)
union all
select 'aantal spelers',       (select count(*)::text from public.pool_members)
union all
select 'races in 2026',        (select count(*)::text from public.races where season = 2026)
union all
select 'races met deelnemerslijst',
       (select count(*)::text from public.races where season = 2026 and drivers is not null)
union all
select 'handmatig ingevulde uitslagen',
       (select count(*)::text from public.races
        where season = 2026 and (quali_handmatig or race_handmatig))
union all
select 'vragen in de lijst',
       case when (select count(*) from public.questions) = 9
       then 'ok' else (select count(*)::text from public.questions) end
union all
select 'punten Simpel / Klassiek / Gevorderd',
       (select
          (select sum(punten)::text from public.questions
           where id in ('quali_top10','race_top10')) || ' / ' ||
          (select sum(punten)::text from public.questions
           where id in ('quali_top10','race_top10','winnaar','pole','snelste_ronde')) || ' / ' ||
          (select sum(punten)::text from public.questions))
union all
select 'winnaar ingevuld',
       (select count(*)::text from public.answers where question_id = 'winnaar')
union all
select 'ingevulde antwoorden',   (select count(*)::text from public.answers)
union all
-- Blijft staan zolang niet zeker is dat alles goed is overgezet; de app
-- leest deze tabel niet meer.
select 'oude voorspellingen (ongebruikt)', (select count(*)::text from public.predictions);
